version: '3'
services:
  jakartaEE:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: brunoe/samplejee91restapp
    environment:
      - ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
      - "8181:8181"
      - "4848:4848"
      - "8686:8686"
    depends_on:
      - db
  db:
    image: brunoe/h2:develop
    ports:
      - "8082:8082"
      - "9092:9092"
    environment:
        H2_OPTIONS: '-ifNotExists -webAllowOthers -tcpAllowOthers -pgAllowOthers -ifNotExists'
    volumes:
      - h2data:/h2-data

volumes:
  h2data: