name: Docker Image CI

#on:
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]
    
# on every push
on: [push]    

jobs:

  maven-build:

    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for branch ${GITHUB_REF_NAME}
      run: DOCKER_BUILDKIT=1 docker build . --build-arg GITHUBLOGIN --build-arg GITHUBPASSWORD --build-arg SONAR_URL --build-arg SONAR_TOKEN --file ./docker/Dockerfile --tag brunoe/samplejee91:${GITHUB_REF_NAME}
